# Generated by Django 5.2.10 on 2026-01-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_project_contributors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
