# Generated by Django 5.2.10 on 2026-01-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_comment_author_alter_issue_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuid',
            new_name='id',
        ),
    ]
