# Generated by Django 5.2.10 on 2026-02-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_rename_uuid_comment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
    ]
