# Generated by Django 5.2.10 on 2026-02-02 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
